/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pid.exercise.search;

/**
 * The purpose of this class is to provide static methods for searching integer arrays and does not need to be
 * instantiated.
 */
public class Search {

    public static int linearSearch(int[] array, int value) {
        // TODO Implement linear search
        return 0;
    }

    public static int binarySearch(int[] array, int value) {
        // TODO Implement iterative binary search
        return 0;
    }

    public static int binarySearchRecursive(int[] array, int value) {
        // TODO Implement recursive binary search
        return 0;
    }

}
